wip 17

diff --git a/.github/workflows/debuggha.yml b/.github/workflows/debuggha.yml
--- a/.github/workflows/debuggha.yml
+++ b/.github/workflows/debuggha.yml
@@ -26,6 +26,24 @@ jobs:
     - name: "Checkout"
       uses: actions/checkout@v3.2.0
 
+    - name: Test ARM Templates - path
+      id: armttktest
+      uses: aliencube/arm-ttk-actions@v0.3
+      with:
+        path: ${{ env.ARMPath }}
+
+    - name: Test result - path
+      shell: bash
+      continue-on-error: false
+      run: |
+        result=$(echo "${{ steps.armttktest.outputs.results }}" | jq '.[].Passed')
+        if [[ "$result" =~ .*"false".* ]]; then
+          echo "Errors found in ARM-TTK check!"
+          exit 1
+        else
+          exit 0
+        fi
+
     - name: Azure Login via Az module
       uses: azure/login@v1.4.6
       with:
