ARM TTK test result exit code

diff --git a/.github/workflows/fgt-arm-a-single-vm.yml b/.github/workflows/fgt-arm-a-single-vm.yml
--- a/.github/workflows/fgt-arm-a-single-vm.yml
+++ b/.github/workflows/fgt-arm-a-single-vm.yml
@@ -36,6 +36,13 @@ jobs:
       continue-on-error: true
       run: |
         echo "${{ toJSON(fromJSON(steps.armttktest.outputs.results)) }}"
+        result=`echo "${{ toJSON(fromJSON(steps.armttktest.outputs.results)) }}" | jq '.[].Passed'`
+        if [[ "$result" =~ .*"false".* ]]; then
+          echo "Errors found in ARM-TTK check!"
+          exit 1
+        else
+          exit 0
+        fi
 
     - name: Azure Login via Az module
       uses: azure/login@v1
